# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CircleLineDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CircleLineDemo
  pod 'CRBoxInputView', '1.2.1'
end
